### ISSUE TITLE
Update docs for actions

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/core#249]
Actions in conversation flow now need to define their input attributes (and optionally where to save their output attributes) as of this PR https://github.com/opendialogai/core/pull/210

We need to update the OD docs to reflect this. Would be a good place to document the creation of actions at the same time

This relates to this PR: https://github.com/opendialogai/core/pull/210 that has been merged.

Actions in the conversation flow can now be defined with `input_attributes` and `output_attributes` as follows:
```
            action:
              id: action.core.example
              input_attributes:
                - user.first_name
                - user.last_name
              output_attributes:
                - user.first_name
                - session.full_name
```

And Actions themselves get an update to the `protected $outputsAttributes` array - where it used to have to define the context to pull the attribute from, it now just needs the attribute name.

If an action defines outputsAttributes, they must be supplied in the conversation YAML or the action will not run.
